---
title: "Garlic Noodles"
date: "2023-09-04"
categories: [pasta,avi]
---

## Background

Avi made us [this recipe](https://rasamalaysia.com/garlic-noodles-recipe/) in the summer of 2023 and we loved it.

## Ingredients

- 20 oz. yellow noodles or spaghetti
- 1 tablespoon bottled grated Parmesan cheese

*Garlic Sauce:*

- 1 stick unsalted butter
- 2 tablespoons minced garlic or more to taste
- 1 tablespoon Maggie seasoning sauce
- 1 tablespoon oyster sauce
- 1 tablespoon fish sauce
- 1 tablespoon sugar

## Directions

1. Rinse the yellow noodles with running water to discard the oil from the noodles. Drain and set aside.

1. Heat up a pot of water until boiling. Add the noodles into the boiling water and cook the noodles until al dente (you want it to still have a good chewy bite), or for a few minutes. You can taste the texture of the noodles while cooking. Do not overcook as the noodles will turn soggy. Transfer the noodles out and drain dry.
 
1. Prepare the Garlic Sauce using a saute pan on medium to low heat. Add the butter into the pan and when it melts, add the garlic and saute until aromatic but not browned. Add all the seasonings into the pan, stir to combine well. Transfer the garlic sauce into a small bowl.

1. To serve, just toss all the noodles with the garlic sauce. Add the Parmesan cheese, toss to combine well. Serve immediately.

