---
title: "Creamy Orecchiette with Spring Onions, Fennel, and Bacon"
date: "2023-09-04"
categories: [pasta,bacon,avi]
---

## Background

Avi made [this dish](https://www.seriouseats.com/creamy-orecchiette-with-spring-onions-fennel-and-bacon) for us in Summer 2023, and we loved it.

## Ingredients

* 6 slices (about 6 ounces; 170g) thick-cut bacon
* 1 pound (450g) spring onions, trimmed, white and green parts divided and thinly sliced (see note)
* 1 fennel bulb (about 1 pound; 450g), cored and thinly sliced, fronds reserved
* 1/4 cup (60ml) water
* Kosher salt
* 1/8 teaspoon baking soda
* 1 cup (235ml) heavy cream
* 1 pound (450g) dried orecchiette pasta
* Freshly ground black pepper
* 1 cup (about 3 ounces; 85g) grated Parmigiano-Reggiano, plus extra for serving

## Directions

1. In a large, straight-sided sauté pan or Dutch oven, cook bacon over medium-low heat, turning occasionally, until meaty parts are crisp and fatty parts are tender, 8 to 10 minutes. Using tongs, transfer bacon to a cutting board and reserve rendered bacon fat in the pan. Cut bacon crosswise into 3/4-inch pieces; set aside.

1. Return pan to stovetop and increase heat to medium-high. Add white and light green spring onion parts, fennel, and water, season with salt and cook, stirring frequently with a rubber spatula, until vegetables just begin to soften, about 5 minutes. Add baking soda, stir to combine, and continue to cook until vegetables are very soft and beginning to break down, about 8 minutes longer.

1. Add remaining green parts of spring onions. Cook until well-incorporated with vegetable mixture and just beginning to soften, about 3 minutes. Add cream, bring to a simmer, and cook until mixture is slightly thickened, about 2 minutes.

1. Transfer mixture to a blender and blend on high speed until smooth and emulsified, about 1 minute. Season lightly with salt. Wipe out sauté pan and transfer blended sauce back to the pan, passing through a fine-mesh strainer if desired. Warm sauce over low heat, occasionally scraping down the sides of the pan to prevent skin from forming.

1. Meanwhile, in a pot of salted boiling water, cook orecchiette until just shy of al dente (about 1 minute less than the package directs). Reserve pasta cooking water.

1. Transfer pasta to pan along with 1/2 cup pasta water and bacon, increase heat to high, and cook, stirring rapidly until sauce has thickened slightly and pasta is well-coated, about 1 minute. Remove from heat, season generously with pepper, add Parmigiano, and stir rapidly to combine. Season with salt, if needed. Divide pasta into serving bowls and garnish with reserved fennel fronds. Serve immediately, passing more cheese at the table.
