---
title: "Penne Alla Vodka"
date: "2023-06-12"
image: example.jfif
categories: [pasta,avi]
---

This recipe was first introduced to us by Avi in March 2023. The recipe below is modified from [Serious Eats](https://www.seriouseats.com/pasta-with-vodka-sauce).

## Ingredients

3 T unsalted butter

1 medium (8-ounce) yellow onion, diced

3 medium cloves garlic, thinly sliced

1 t red pepper flakes

Salt

1 can (6oz) tomato paste

1 can (14.5oz) whole peeled tomatoes (diced also works)

1 c heavy cream

1 lb short tubular pasta, such as rigatoni or penne

1/4 c vodka, plus more if desired

2 ounces grated Parmigiano-Reggiano, plus more for serving

## Directions

1.  In a large (3- or 4-quart) saucepan or small Dutch oven, melt butter over medium heat. Add onions, garlic, and red pepper flakes, season lightly with salt, and cook, stirring frequently, until onions are very soft but not browned, about 15 minutes; lower heat if needed to prevent browning.

2.  Add tomato paste and cook, stirring, until tomato paste is fragrant and thick, about 3 minutes. Stir in canned tomatoes with their liquid. Bring to a simmer, then cook, stirring often and crushing the whole tomatoes roughly with a spoon, until sauce has thickened slightly, about 10 minutes.

3.  Add cream, and stir to incorporate. Transfer sauce to a blender, and blend until very smooth (you may be able to make an immersion blender work, but in our tests the sauce level was too low to safely avoid splattering). Wipe out pot, then return blended sauce to it. Season lightly with salt.

4.  In a medium pot of salted boiling water, cook pasta until just shy of al dente, about 3 minutes less than the package directs. About 1 minute before you transfer pasta to sauce, add vodka to tomato sauce and bring to a gentle simmer over medium heat.

5.  Using a spider skimmer or slotted spoon, transfer pasta directly to sauce pot along with 1/2 cup (120ml) pasta water (alternatively, reserve 2 cups pasta water, then drain pasta in a colander, then add to sauce with 1/2 cup of the reserved water). Increase heat to high, and cook, stirring constantly, until pasta is well coated in sauce and reaches the al dente stage, about 3 minutes. If sauce thickens too much before pasta is ready, add more pasta water in 1/4 cup (60ml) increments as needed.

6.  Remove from heat and stir in cheese until thoroughly incorporated into a smooth and creamy sauce. Taste for salt, and season with more if needed. If you can't detect the vodka at all, you can add a few drops more and stir it in before serving; exactly how boozy you want the sauce is a question of taste, but be careful because a heavy hand will ruin the dish. Spoon pasta and sauce onto warmed serving plates and top with additional grated cheese. Serve immediately.

## Notes

A single batch makes approximately 40oz of sauce. Useful when portioning batches for freezing!

If you are re-heating from frozen, add more vodka to taste. I think the extra simmering before freezing may be cooking off the vodka.
