---
title: "Banana Bread"
date: "2023-11-18"
categories: [dessert]
---

Monica Holtzclaw made this for Theodore a number of times in the Fall of 2023, and it was always a big hit!

## Ingredients

-   2 cups all-purpose flour

-   1.5 t baking powder

-   0.5 t baking soda

-   0.25 t salt

-   0.25 t ground cinnamon

-   1/8 t ground nutmeg

-   2 eggs, beaten

-   1.5 cups mashed ripe bananas (\~5 medium)

-   1 cup sugar

-   1/2 cup cooking oil or melted butter

-   1/4 cups chopped walnuts or chocolate chips

## Directions

1.  Preheat oven to 350F
2.  Grease bottom and 1/2 inch up the sides of one 9x5x3-inch or two 7.5x3.5x2-inch loaf pans and set aside.
3.  In a large bowl combine flour, baking powder, baking soda salt, cinnamon, and nutmeg. Make a well in the center of flour mixture and set aside.
4.  In a medium bowl combine eggs, banana, sugar, and oil.
5.  Add egg mixture all at once to the flour mixture. Stir just until moistened. Fold in walnuts or chocolate chips.
6.  Spoon batter into prepared load pan(s).
7.  Bake for 55 to 60 minutes for 9x5x3-inch pan or 40 to 45 minutes for the 7.5x3.5x2-inch loaf pans or until a wooden toothpick inserted into the center comes out clean.
8.  Cool in pan on a wire rack for 10 minutes. Remove from pan and let cool completely on rack.
