---
title: "Chicken Enchiladas"
date: "2023-12-18"
categories: [sjoberg,chicken]
---

## Ingredients

-   1 Onion, chopped

-   2 T Olive Oil

-   Butter for greasing

-   1 Costco Rotisserie Chicken

-   2 cups cooked rice

-   Juice of one lime

-   2 T Cilantro, chopped

-   1 can black beans

-   28 oz can green enchilada sauce

-   Tortillas, preferably freshly cooked. You can likely buy uncooked at Costco

-   Shredded cheese

## Directions

1.  Preheat oven to 350F
2.  \_Optional\_: Saute chopped onion with olive oil.
3.  Combine sauteed onions, chicken meat broken into bite-size pieces, rice, lime juice, cilantro, black beans, and half of the enchilada sauce in a large bowl.
4.  Butter a 9x13 pan
5.  Fill each tortilla with 2 heaping spoonfuls of filling and roll enchilada. Place in 9x13 pan. Continue until pan is full.
6.  Top with the other half of the enchilada sauce and cheese.
7.  Place in oven until cheese bubbles. Cook times vary based on whether the dish is room temperature or whether it was prepared in advance in placed in a refrigerator.
